<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Library</OutputType>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <Deterministic>true</Deterministic>
        <AssemblyName>TypeShell</AssemblyName>
        <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
        <RootNamespace>TypeShell</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Antlr4.Runtime.Standard" Version="4.13.1" />
        <PackageReference Include="Antlr4BuildTasks" Version="12.14.0" />
        <PackageReference Include="System.Management.Automation" Version="7.5.0" />
    </ItemGroup>

    <ItemGroup>
        <Antlr4 Include="TypeShell.g4" />
    </ItemGroup>

    <Target Name="CopyToModuleRoot" AfterTargets="Build">
        <ItemGroup>
            <ModuleFiles Include="$(OutputPath)*.dll" />
        </ItemGroup>
        <Copy SourceFiles="@(ModuleFiles)" DestinationFolder="$(ProjectDir)output\" />
    </Target>
</Project>